version: 0.2
env:
  variables:
    REPOSITORY: cdk-auto-build
phases:
  build:
    runtime-versions:
      docker: 18
    commands:
      - make push
  post_build:
    commands:
      - aws ecr list-images --repository-name ${REPOSITORY}
